name: Release

on:
  release:
    types: [ published ]

jobs:

  build:

    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Set output
        id: vars
        run: echo ::set-output name=tag::${GITHUB_REF#refs/*/}

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            bishoybasily/toolbox:latest
            bishoybasily/toolbox:${{ steps.vars.outputs.tag }}

